### ISSUE TITLE
Relations should be in camelCase

### ISSUE THREAD

**Issue by genesiscz** [scrumble-nl/laravel-model-ts-type#10]
it si generally known that relation properties are being named with camelCase. Maybe add an option to use camel, or maybe even better, use camelCase if the @property exists, and fallback to snake_case?

**Comment by Luukdewaaier** [comment]
@genesiscz Laravel automatically converts the names of relationships from camelCase to snake_case when the model is converted to an array (toArray()) or json (toJson()). As this is always happening (if i am not mistaken) when you are using the model in TypeScript it should be snake_case. If you still need this feature I will add it!

**Comment by genesiscz** [comment]
There's 	`public static $snakeAttributes` in Models
Maybe take it into the decision?

**Comment by Luukdewaaier** [comment]
This is fixed in the latest release
