### ISSUE TITLE
Undefined array key "operator"

### ISSUE THREAD

**Issue by thekonz** [scrumble-nl/laravel-model-ts-type#15]
The `CastsPropertyMutator` does not check if the `$propertyDefinition[$key]` exists and could generate a property definition like this:
```php
[
    'value' => 'boolean'
]
```
This is missing the `operator` key and that leads to an error in `GenerateTypesCommand::formatContents`.

Not the biggest issue in a well configured project, but in development I had a model with a `$casts` property for a column that I had removed (I just did not clean up the `$casts` array).

Maybe a warning and skipping that line would be helpful instead of breaking. I will open a PR.

**Comment by Luukdewaaier** [comment]
I ran into this issue before, it would indeed be a great addition. Looking forward to your PR.

**Comment by Luukdewaaier** [comment]
Closed with #17
