### ISSUE TITLE
Include results in an error

### ISSUE THREAD

**Issue by thekonz** [scrumble-nl/laravel-model-ts-type#16]
I have a trait in a sub-directory of the `app/Models` directory.
`GenerateTypesCommand::handle` tries to `include` this trait, because it is not a declared class yet.

```php
        foreach ($this->modelHits as $model) {
            $namespace = format_namespace($model);

            if (!in_array($namespace, get_declared_classes())) {
                include($model);
            }
```

This results in an error like this:
![grafik](https://user-images.githubusercontent.com/2700089/115008294-3de5d200-9eab-11eb-8165-101f90fcb74b.png)

Why is there even an include in here? Why don't you just rely on composer autoloading?

**Comment by Luukdewaaier** [comment]
That would probably be the better way to go, will be looking into this in the future! Thanks for the feedback.

**Comment by scrumble-niels** [comment]
This issue is fixed with the latest release.
