### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by tekord** [scrumble-nl/laravel-model-ts-type#20]
Hi! This package cannot be installed on Laravel 9, it requires laravel/framework ^8.0. Is it possible to upgrade the package to make it available for Laravel 9?

**Comment by tekord** [comment]
I tried to change the requirements locally (php 8 + laravel 9) and it works well. So, you just need to update the composer.json file.

**Comment by Luukdewaaier** [comment]
Your PR has been merged
