### ISSUE TITLE
Add semicolons to the end of generated types or an option to allow this

### ISSUE THREAD

**Issue by NattieGit** [scrumble-nl/laravel-model-ts-type#26]
Developers using eslint with the rule [@typescript-eslint/semi](https://typescript-eslint.io/rules/semi) will encounter errors with the default generated types, as they do not end with a semicolon.

It would be nice to either add semicolons by default, or be able to specify this in the options with the `artisan types:generate` command.

The expected output of a simple model type would be:

```
type Interest = {
  id: number;
  name: string;
};
```

This would be beneficial as it means we could happily rerun the artisan generate command each time a new model is added and have the declaration file in the format expected by our environment.

Thanks for your time and for developing this package :)

**Comment by Luukdewaaier** [comment]
Thanks for the feedback, we will start adding the semicolon by default. I will update this when it is released.

**Comment by Luukdewaaier** [comment]
This has been implemented in #37, it will be in the next release.

**Comment by Luukdewaaier** [comment]
This has been implemented in the latest release 10.1.0.
