### ISSUE TITLE
Generating types for Resources

### ISSUE THREAD

**Issue by gcjbr** [scrumble-nl/laravel-model-ts-type#32]
I use resources a lot, and they can be a whole lot different in structure than the actual Model. Right now I'm generating types form them by hand.

I'm just wondering if there's enough interest on adding this to the package or is just a niche use case. 

If community seems interested I'll get on to adding it

**Comment by Luukdewaaier** [comment]
If there is more support from the community we can add this feature. You are always welcome to add it yourself!
