### ISSUE TITLE
Methods with Union Types throw "undefined method ReflectionUnionType::getName()" Error

### ISSUE THREAD

**Issue by SaintPeter** [scrumble-nl/laravel-model-ts-type#33]
### Description
When parsing a model which has a "Union" return type, IE: `string | int | null`, the types:generate command throws an error "Call to undefined method ReflectionUnionType::getName()"

Full Output:
```
 Call to undefined method ReflectionUnionType::getName()

  at C:\wamp64\www\threshold\vendor\scrumble-nl\laravel-model-ts-type\src\Support\Generators\RelationPropertyGenerator.php:58
     54▕      */
     55▕     private function getReturnType(\ReflectionMethod $method): string
     56▕     {
     57▕         if (null !== ($returnType = $method->getReturnType())) {
  ➜  58▕             return $returnType->getName();
     59▕         }
     60▕
     61▕         $docComment = $method->getDocComment();
     62▕

  1   C:\wamp64\www\threshold\vendor\scrumble-nl\laravel-model-ts-type\src\Support\Generators\RelationPropertyGenerator.php:26
      Scrumble\TypeGenerator\Support\Generators\RelationPropertyGenerator::getReturnType(Object(ReflectionMethod))

  2   C:\wamp64\www\threshold\vendor\scrumble-nl\laravel-model-ts-type\src\Console\Commands\GenerateTypesCommand.php:183
      Scrumble\TypeGenerator\Support\Generators\RelationPropertyGenerator::getPropertyDefinition(Object(App\Models\ClosetPoItem))
```

Stepping through this code shows that some method have has a [ReflectionUnionType](https://www.php.net/manual/en/class.reflectionuniontype.php) type, which doesn't have a `getReturnType` method (From [ReflectionNamedType](https://www.php.net/manual/en/class.reflectionnamedtype.php)), instead it has a `getTypes` method which returns an array of types.

## Steps to Reproduce
1) Create a New Model
2) Add a public method with a type `string | int`
      ```php
      public function someTest(): string | int {
          return 'test!';
      }
      ```
3) Run `php artisan types:generate`

## Workaround
I modified `RelationProperyGenerator->getReturnType` to skip return types which don't have the `getName` method.
```php
if (null !== ($returnType = $method->getReturnType())) {
    if(method_exists($returnType, 'getName')) {
        return $returnType->getName();                
    }
}
 ```

## System Information
PHP: 8.0.15
Laravel: 9.52.7

**Comment by Luukdewaaier** [comment]
Fixed this in the latest release 10.1.1
