### ISSUE TITLE
Morph relations type generation

### ISSUE THREAD

**Issue by OliverBeckwith** [scrumble-nl/laravel-model-ts-type#43]
I understand why we resolve a morph to `any`/`any[]` from the model that has the morph type and ID, but a relation going back via a `MorphMany` etc. could likely be resolved without issue. I am unsure of exactly which return types are safe to resolve here (otherwise would make a PR myself), but I think `MorphOne` and `MorphMany` are the obvious ones that can likely be resolved to a type safely. 

[Responsible lines](https://github.com/scrumble-nl/laravel-model-ts-type/blob/5f06e602aea3f6b9167821c67eb056aab33600a4/src/Support/Generators/RelationPropertyGenerator.php#L132C9-L134C10)

**Comment by Luukdewaaier** [comment]
HI @OliverBeckwith, we have just implemented this in the latest release (10.4.0). Thanks to @stijn-vergauwen.
