### ISSUE TITLE
Ap\ namespace 

### ISSUE THREAD

**Issue by genesiscz** [scrumble-nl/laravel-model-ts-type#9]
format_namespace function cuts my $namespace `App\\Models\\` and generate `Ap\Models\` namespace because 

```php
$namespace = 'A' . substr($namespace,2); // should be 1
// or better $namespace = ucfirst($namespace);
```

`$path is app/Models/ModelName.php` so substr with offset 2 starts with the latter p.

Otherwise an amazing library! Thanks!

**Comment by Luukdewaaier** [comment]
@genesiscz When does this happen? The substr has an offset of 2 because it is prepended by a slash.

**Comment by genesiscz** [comment]
`php artisan types:generate --modelDir=app/Models/ --outputDir=app/ModelsTypescript/ --namespace=App\\Models --noKebabCase`

modelHits have relative paths, starting with app/

app_path("Models") is /data/xx/app/Models

I understand that base_path() is replaced, so just maybe remove the slash in the first place?

```patch
        -$namespace = str_replace(base_path(), '', $path);
        +$namespace = str_replace(base_path()."/", '', $path);
```

**Comment by Luukdewaaier** [comment]
This is fixed in the latest release
